// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/home/models/Keyboard.glb --types true --keepnames --keepgroups true --meta true --shadows true --precision 5
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Keyboard: THREE.Mesh
    ArrowDown: THREE.Mesh
    DownArrow: THREE.Mesh
    ArrowLeft: THREE.Mesh
    LeftArrow: THREE.Mesh
    ArrowRight: THREE.Mesh
    RightArrow: THREE.Mesh
    ArrowUp: THREE.Mesh
    UpArrow: THREE.Mesh
    ESC: THREE.Mesh
    Text: THREE.Mesh
    F1: THREE.Mesh
    Text001: THREE.Mesh
    F10: THREE.Mesh
    Text010: THREE.Mesh
    F11: THREE.Mesh
    Text011: THREE.Mesh
    F12: THREE.Mesh
    Text012: THREE.Mesh
    F2: THREE.Mesh
    Text002: THREE.Mesh
    F3: THREE.Mesh
    Text003: THREE.Mesh
    F4: THREE.Mesh
    Text004: THREE.Mesh
    F5: THREE.Mesh
    Text005: THREE.Mesh
    F6: THREE.Mesh
    Text006: THREE.Mesh
    F7: THREE.Mesh
    Text007: THREE.Mesh
    F8: THREE.Mesh
    Text008: THREE.Mesh
    F9: THREE.Mesh
    Text009: THREE.Mesh
    Key014: THREE.Mesh
    Text015: THREE.Mesh
    Key015: THREE.Mesh
    Text080: THREE.Mesh
    Key016: THREE.Mesh
    Text013: THREE.Mesh
    Key017: THREE.Mesh
    Text014: THREE.Mesh
    Key018: THREE.Mesh
    Text077: THREE.Mesh
    Key019: THREE.Mesh
    Text079: THREE.Mesh
    Key020: THREE.Mesh
    Text086: THREE.Mesh
    Key021: THREE.Mesh
    Text087: THREE.Mesh
    Key022: THREE.Mesh
    Text081: THREE.Mesh
    Key023: THREE.Mesh
    Text019: THREE.Mesh
    Key024: THREE.Mesh
    Text018: THREE.Mesh
    Key029: THREE.Mesh
    Text017: THREE.Mesh
    Key030: THREE.Mesh
    Text016: THREE.Mesh
    Key031: THREE.Mesh
    Text028: THREE.Mesh
    Key032: THREE.Mesh
    Text020: THREE.Mesh
    Key033: THREE.Mesh
    Text021: THREE.Mesh
    Key034: THREE.Mesh
    Text022: THREE.Mesh
    Key035: THREE.Mesh
    Text023: THREE.Mesh
    Key036: THREE.Mesh
    Text024: THREE.Mesh
    Key037: THREE.Mesh
    Text025: THREE.Mesh
    Key038: THREE.Mesh
    Text026: THREE.Mesh
    Key039: THREE.Mesh
    Text027: THREE.Mesh
    Key040: THREE.Mesh
    Text042: THREE.Mesh
    Key041: THREE.Mesh
    Text031: THREE.Mesh
    Key042: THREE.Mesh
    Text032: THREE.Mesh
    Key043: THREE.Mesh
    Text033: THREE.Mesh
    Key044: THREE.Mesh
    Text034: THREE.Mesh
    Key045: THREE.Mesh
    Text035: THREE.Mesh
    Key046: THREE.Mesh
    Text036: THREE.Mesh
    Key047: THREE.Mesh
    Text037: THREE.Mesh
    Key048: THREE.Mesh
    Text038: THREE.Mesh
    Key049: THREE.Mesh
    Text039: THREE.Mesh
    Key050: THREE.Mesh
    Text040: THREE.Mesh
    Key051: THREE.Mesh
    Text041: THREE.Mesh
    Key052: THREE.Mesh
    Text056: THREE.Mesh
    Key053: THREE.Mesh
    Text069: THREE.Mesh
    Key054: THREE.Mesh
    Text084: THREE.Mesh
    Key055: THREE.Mesh
    Text074: THREE.Mesh
    Key056: THREE.Mesh
    Wizard002: THREE.Mesh
    Key057: THREE.Mesh
    Text082: THREE.Mesh
    Key058: THREE.Mesh
    Wizard001: THREE.Mesh
    Key059: THREE.Mesh
    Text059: THREE.Mesh
    Key060: THREE.Mesh
    Text060: THREE.Mesh
    Key061: THREE.Mesh
    Text061: THREE.Mesh
    Key062: THREE.Mesh
    Text062: THREE.Mesh
    Key063: THREE.Mesh
    Text063: THREE.Mesh
    Key064: THREE.Mesh
    Text064: THREE.Mesh
    Key065: THREE.Mesh
    Text065: THREE.Mesh
    Key066: THREE.Mesh
    Text066: THREE.Mesh
    Key067: THREE.Mesh
    Text067: THREE.Mesh
    Key068: THREE.Mesh
    Text068: THREE.Mesh
    Key069: THREE.Mesh
    Text045: THREE.Mesh
    Key070: THREE.Mesh
    Text046: THREE.Mesh
    Key071: THREE.Mesh
    Text047: THREE.Mesh
    Key072: THREE.Mesh
    Text048: THREE.Mesh
    Key073: THREE.Mesh
    Text049: THREE.Mesh
    Key074: THREE.Mesh
    Text050: THREE.Mesh
    Key075: THREE.Mesh
    Text051: THREE.Mesh
    Key076: THREE.Mesh
    Text052: THREE.Mesh
    Key077: THREE.Mesh
    Text053: THREE.Mesh
    Key078: THREE.Mesh
    Text054: THREE.Mesh
    Key079: THREE.Mesh
    Text055: THREE.Mesh
    Key080: THREE.Mesh
    Text105: THREE.Mesh
    Key081: THREE.Mesh
    Text089: THREE.Mesh
    Key082: THREE.Mesh
    Text098: THREE.Mesh
    Key083: THREE.Mesh
    Text095: THREE.Mesh
    Key084: THREE.Mesh
    Text092: THREE.Mesh
    Key085: THREE.Mesh
    Text093: THREE.Mesh
    Key086: THREE.Mesh
    Text096: THREE.Mesh
    Key087: THREE.Mesh
    Text099: THREE.Mesh
    Key088: THREE.Mesh
    Text102: THREE.Mesh
    Key089: THREE.Mesh
    Text090: THREE.Mesh
    Key090: THREE.Mesh
    Text091: THREE.Mesh
    Key091: THREE.Mesh
    Text094: THREE.Mesh
    Key092: THREE.Mesh
    Text097: THREE.Mesh
    Key093: THREE.Mesh
    Text088: THREE.Mesh
    Keys001: THREE.Mesh
    Text085: THREE.Mesh
    Keys002: THREE.Mesh
    Text058: THREE.Mesh
    Keys003: THREE.Mesh
    Text070: THREE.Mesh
    Keys004: THREE.Mesh
    Text072: THREE.Mesh
    Keys005: THREE.Mesh
    Text044: THREE.Mesh
    Keys006: THREE.Mesh
    Text030: THREE.Mesh
    Keys007: THREE.Mesh
    Text029: THREE.Mesh
    Keys008: THREE.Mesh
    Text100: THREE.Mesh
    Keys009: THREE.Mesh
    Text103: THREE.Mesh
    Keys010: THREE.Mesh
    Text104: THREE.Mesh
    Keys011: THREE.Mesh
    Text057: THREE.Mesh
    Keys012: THREE.Mesh
    Plane: THREE.Mesh
  }
  materials: {
    ['Plastic.001']: THREE.MeshStandardMaterial
    Keycap: THREE.MeshStandardMaterial
    KeyText: THREE.MeshStandardMaterial
  }
}

type ActionName =
  | 'Keyboard'
  | 'ArrowDown'
  | 'DownArrow'
  | 'ArrowLeft'
  | 'LeftArrow'
  | 'ArrowRight'
  | 'RightArrow'
  | 'ArrowUp'
  | 'UpArrow'
  | 'ESC'
  | 'Text'
  | 'F1'
  | 'Text.001'
  | 'F10'
  | 'Text.010'
  | 'F11'
  | 'Text.011'
  | 'F12'
  | 'Text.012'
  | 'F2'
  | 'Text.002'
  | 'F3'
  | 'Text.003'
  | 'F4'
  | 'Text.004'
  | 'F5'
  | 'Text.005'
  | 'F6'
  | 'Text.006'
  | 'F7'
  | 'Text.007'
  | 'F8'
  | 'Text.008'
  | 'F9'
  | 'Text.009'
  | 'Key.014'
  | 'Text.015'
  | 'Key.015'
  | 'Text.080'
  | 'Key.016'
  | 'Text.013'
  | 'Key.017'
  | 'Text.014'
  | 'Key.018'
  | 'Text.077'
  | 'Key.019'
  | 'Text.079'
  | 'Key.020'
  | 'Text.086'
  | 'Key.021'
  | 'Text.087'
  | 'Key.022'
  | 'Text.081'
  | 'Key.023'
  | 'Text.019'
  | 'Key.024'
  | 'Text.018'
  | 'Key.029'
  | 'Text.017'
  | 'Key.030'
  | 'Text.016'
  | 'Key.031'
  | 'Text.028'
  | 'Key.032'
  | 'Text.020'
  | 'Key.033'
  | 'Text.021'
  | 'Key.034'
  | 'Text.022'
  | 'Key.035'
  | 'Text.023'
  | 'Key.036'
  | 'Text.024'
  | 'Key.037'
  | 'Text.025'
  | 'Key.038'
  | 'Text.026'
  | 'Key.039'
  | 'Text.027'
  | 'Key.040'
  | 'Text.042'
  | 'Key.041'
  | 'Text.031'
  | 'Key.042'
  | 'Text.032'
  | 'Key.043'
  | 'Text.033'
  | 'Key.044'
  | 'Text.034'
  | 'Key.045'
  | 'Text.035'
  | 'Key.046'
  | 'Text.036'
  | 'Key.047'
  | 'Text.037'
  | 'Key.048'
  | 'Text.038'
  | 'Key.049'
  | 'Text.039'
  | 'Key.050'
  | 'Text.040'
  | 'Key.051'
  | 'Text.041'
  | 'Key.052'
  | 'Text.056'
  | 'Key.053'
  | 'Text.069'
  | 'Key.054'
  | 'Text.084'
  | 'Key.055'
  | 'Text.074'
  | 'Key.056'
  | 'Wizard.002'
  | 'Key.057'
  | 'Text.082'
  | 'Key.058'
  | 'Wizard.001'
  | 'Key.059'
  | 'Text.059'
  | 'Key.060'
  | 'Text.060'
  | 'Key.061'
  | 'Text.061'
  | 'Key.062'
  | 'Text.062'
  | 'Key.063'
  | 'Text.063'
  | 'Key.064'
  | 'Text.064'
  | 'Key.065'
  | 'Text.065'
  | 'Key.066'
  | 'Text.066'
  | 'Key.067'
  | 'Text.067'
  | 'Key.068'
  | 'Text.068'
  | 'Key.069'
  | 'Text.045'
  | 'Key.070'
  | 'Text.046'
  | 'Key.071'
  | 'Text.047'
  | 'Key.072'
  | 'Text.048'
  | 'Key.073'
  | 'Text.049'
  | 'Key.074'
  | 'Text.050'
  | 'Key.075'
  | 'Text.051'
  | 'Key.076'
  | 'Text.052'
  | 'Key.077'
  | 'Text.053'
  | 'Key.078'
  | 'Text.054'
  | 'Key.079'
  | 'Text.055'
  | 'Key.080'
  | 'Text.105'
  | 'Key.081'
  | 'Text.089'
  | 'Key.082'
  | 'Text.098'
  | 'Key.083'
  | 'Text.095'
  | 'Key.084'
  | 'Text.092'
  | 'Key.085'
  | 'Text.093'
  | 'Key.086'
  | 'Text.096'
  | 'Key.087'
  | 'Text.099'
  | 'Key.088'
  | 'Text.102'
  | 'Key.089'
  | 'Text.090'
  | 'Key.090'
  | 'Text.091'
  | 'Key.091'
  | 'Text.094'
  | 'Key.092'
  | 'Text.097'
  | 'Key.093'
  | 'Text.088'
  | 'Keys.001'
  | 'Text.085'
  | 'Keys.002'
  | 'Text.058'
  | 'Keys.003'
  | 'Text.070'
  | 'Keys.004'
  | 'Text.072'
  | 'Keys.005'
  | 'Text.044'
  | 'Keys.006'
  | 'Text.030'
  | 'Keys.007'
  | 'Text.029'
  | 'Keys.008'
  | 'Text.100'
  | 'Keys.009'
  | 'Text.103'
  | 'Keys.010'
  | 'Text.104'
  | 'Keys.011'
  | 'Text.057'
  | 'Keys.012'
  | 'Plane'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/home/models/Keyboard.glb') as unknown as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group animations={actions} ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Keyboard" castShadow receiveShadow geometry={nodes.Keyboard.geometry} material={materials['Plastic.001']} position={[-0.04597, 0.01744, 0.15003]} userData={{ name: 'Keyboard' }}>
          <mesh name="ArrowDown" castShadow receiveShadow geometry={nodes.ArrowDown.geometry} material={materials.Keycap} position={[0.1553, 0.0078, 0.06712]} userData={{ name: 'ArrowDown' }}>
            <mesh name="DownArrow" castShadow receiveShadow geometry={nodes.DownArrow.geometry} material={materials.KeyText} position={[0.00019, 0.00508, 0.00045]} scale={0.596} userData={{ name: 'DownArrow' }} />
          </mesh>
          <mesh name="ArrowLeft" castShadow receiveShadow geometry={nodes.ArrowLeft.geometry} material={materials.Keycap} position={[0.13112, 0.0078, 0.06712]} userData={{ name: 'ArrowLeft' }}>
            <mesh name="LeftArrow" castShadow receiveShadow geometry={nodes.LeftArrow.geometry} material={materials.KeyText} position={[0, 0.00508, 0.00045]} scale={0.596} userData={{ name: 'LeftArrow' }} />
          </mesh>
          <mesh name="ArrowRight" castShadow receiveShadow geometry={nodes.ArrowRight.geometry} material={materials.Keycap} position={[0.17948, 0.0078, 0.06712]} userData={{ name: 'ArrowRight' }}>
            <mesh name="RightArrow" castShadow receiveShadow geometry={nodes.RightArrow.geometry} material={materials.KeyText} position={[0, 0.00508, 0.00045]} scale={0.596} userData={{ name: 'RightArrow' }} />
          </mesh>
          <mesh name="ArrowUp" castShadow receiveShadow geometry={nodes.ArrowUp.geometry} material={materials.Keycap} position={[0.1553, 0.0078, 0.04274]} userData={{ name: 'ArrowUp' }}>
            <mesh name="UpArrow" castShadow receiveShadow geometry={nodes.UpArrow.geometry} material={materials.KeyText} position={[0.00019, 0.00508, 0.00045]} scale={0.596} userData={{ name: 'UpArrow' }} />
          </mesh>
          <mesh name="ESC" castShadow receiveShadow geometry={nodes.ESC.geometry} material={materials.Keycap} position={[-0.2541, 0.0078, -0.0754]} userData={{ name: 'ESC' }}>
            <mesh name="Text" castShadow receiveShadow geometry={nodes.Text.geometry} material={materials.KeyText} position={[0, 0.00565, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text' }} />
          </mesh>
          <mesh name="F1" castShadow receiveShadow geometry={nodes.F1.geometry} material={materials.Keycap} position={[-0.20613, 0.0078, -0.0754]} userData={{ name: 'F1' }}>
            <mesh name="Text001" castShadow receiveShadow geometry={nodes.Text001.geometry} material={materials.KeyText} position={[0.00051, 0.00565, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.001' }} />
          </mesh>
          <mesh name="F10" castShadow receiveShadow geometry={nodes.F10.geometry} material={materials.Keycap} position={[0.04105, 0.0078, -0.0754]} userData={{ name: 'F10' }}>
            <mesh name="Text010" castShadow receiveShadow geometry={nodes.Text010.geometry} material={materials.KeyText} position={[0.00088, 0.00565, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.010' }} />
          </mesh>
          <mesh name="F11" castShadow receiveShadow geometry={nodes.F11.geometry} material={materials.Keycap} position={[0.06523, 0.0078, -0.0754]} userData={{ name: 'F11' }}>
            <mesh name="Text011" castShadow receiveShadow geometry={nodes.Text011.geometry} material={materials.KeyText} position={[-0.00054, 0.00565, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.011' }} />
          </mesh>
          <mesh name="F12" castShadow receiveShadow geometry={nodes.F12.geometry} material={materials.Keycap} position={[0.08941, 0.0078, -0.0754]} userData={{ name: 'F12' }}>
            <mesh name="Text012" castShadow receiveShadow geometry={nodes.Text012.geometry} material={materials.KeyText} position={[-0.00089, 0.00565, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.012' }} />
          </mesh>
          <mesh name="F2" castShadow receiveShadow geometry={nodes.F2.geometry} material={materials.Keycap} position={[-0.18195, 0.0078, -0.0754]} userData={{ name: 'F2' }}>
            <mesh name="Text002" castShadow receiveShadow geometry={nodes.Text002.geometry} material={materials.KeyText} position={[-0.00068, 0.00565, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.002' }} />
          </mesh>
          <mesh name="F3" castShadow receiveShadow geometry={nodes.F3.geometry} material={materials.Keycap} position={[-0.15778, 0.0078, -0.0754]} userData={{ name: 'F3' }}>
            <mesh name="Text003" castShadow receiveShadow geometry={nodes.Text003.geometry} material={materials.KeyText} position={[-0.00042, 0.00565, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.003' }} />
          </mesh>
          <mesh name="F4" castShadow receiveShadow geometry={nodes.F4.geometry} material={materials.Keycap} position={[-0.1336, 0.0078, -0.0754]} userData={{ name: 'F4' }}>
            <mesh name="Text004" castShadow receiveShadow geometry={nodes.Text004.geometry} material={materials.KeyText} position={[-0.00014, 0.00565, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.004' }} />
          </mesh>
          <mesh name="F5" castShadow receiveShadow geometry={nodes.F5.geometry} material={materials.Keycap} position={[-0.09478, 0.0078, -0.0754]} userData={{ name: 'F5' }}>
            <mesh name="Text005" castShadow receiveShadow geometry={nodes.Text005.geometry} material={materials.KeyText} position={[-0.00056, 0.00565, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.005' }} />
          </mesh>
          <mesh name="F6" castShadow receiveShadow geometry={nodes.F6.geometry} material={materials.Keycap} position={[-0.0706, 0.0078, -0.0754]} userData={{ name: 'F6' }}>
            <mesh name="Text006" castShadow receiveShadow geometry={nodes.Text006.geometry} material={materials.KeyText} position={[-0.00002, 0.00565, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.006' }} />
          </mesh>
          <mesh name="F7" castShadow receiveShadow geometry={nodes.F7.geometry} material={materials.Keycap} position={[-0.04642, 0.0078, -0.0754]} userData={{ name: 'F7' }}>
            <mesh name="Text007" castShadow receiveShadow geometry={nodes.Text007.geometry} material={materials.KeyText} position={[0.00052, 0.00565, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.007' }} />
          </mesh>
          <mesh name="F8" castShadow receiveShadow geometry={nodes.F8.geometry} material={materials.Keycap} position={[-0.02225, 0.0078, -0.0754]} userData={{ name: 'F8' }}>
            <mesh name="Text008" castShadow receiveShadow geometry={nodes.Text008.geometry} material={materials.KeyText} position={[-0.0009, 0.00565, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.008' }} />
          </mesh>
          <mesh name="F9" castShadow receiveShadow geometry={nodes.F9.geometry} material={materials.Keycap} position={[0.01688, 0.0078, -0.0754]} userData={{ name: 'F9' }}>
            <mesh name="Text009" castShadow receiveShadow geometry={nodes.Text009.geometry} material={materials.KeyText} position={[0.00034, 0.00565, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.009' }} />
          </mesh>
          <mesh name="Key014" castShadow receiveShadow geometry={nodes.Key014.geometry} material={materials.Keycap} position={[0.17948, 0.0078, -0.0754]} userData={{ name: 'Key.014' }}>
            <mesh name="Text015" castShadow receiveShadow geometry={nodes.Text015.geometry} material={materials.KeyText} position={[0.00008, 0.00565, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.015' }} />
          </mesh>
          <mesh name="Key015" castShadow receiveShadow geometry={nodes.Key015.geometry} material={materials.Keycap} position={[0.17948, 0.0078, -0.00536]} userData={{ name: 'Key.015' }}>
            <mesh name="Text080" castShadow receiveShadow geometry={nodes.Text080.geometry} material={materials.KeyText} position={[0.00038, 0.00565, 0.00156]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.080' }} />
          </mesh>
          <mesh name="Key016" castShadow receiveShadow geometry={nodes.Key016.geometry} material={materials.Keycap} position={[0.13112, 0.0078, -0.0754]} userData={{ name: 'Key.016' }}>
            <mesh name="Text013" castShadow receiveShadow geometry={nodes.Text013.geometry} material={materials.KeyText} position={[0.00043, 0.00565, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.013' }} />
          </mesh>
          <mesh name="Key017" castShadow receiveShadow geometry={nodes.Key017.geometry} material={materials.Keycap} position={[0.1553, 0.0078, -0.0754]} userData={{ name: 'Key.017' }}>
            <mesh name="Text014" castShadow receiveShadow geometry={nodes.Text014.geometry} material={materials.KeyText} position={[0.00043, 0.00565, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.014' }} />
          </mesh>
          <mesh name="Key018" castShadow receiveShadow geometry={nodes.Key018.geometry} material={materials.Keycap} position={[0.13112, 0.0078, -0.00536]} userData={{ name: 'Key.018' }}>
            <mesh name="Text077" castShadow receiveShadow geometry={nodes.Text077.geometry} material={materials.KeyText} position={[-0.00019, 0.00565, 0.00174]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.077' }} />
          </mesh>
          <mesh name="Key019" castShadow receiveShadow geometry={nodes.Key019.geometry} material={materials.Keycap} position={[0.1553, 0.0078, -0.00536]} userData={{ name: 'Key.019' }}>
            <mesh name="Text079" castShadow receiveShadow geometry={nodes.Text079.geometry} material={materials.KeyText} position={[0.00009, 0.00565, 0.00128]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.079' }} />
          </mesh>
          <mesh name="Key020" castShadow receiveShadow geometry={nodes.Key020.geometry} material={materials.Keycap} position={[0.1553, 0.0078, -0.02981]} userData={{ name: 'Key.020' }}>
            <mesh name="Text086" castShadow receiveShadow geometry={nodes.Text086.geometry} material={materials.KeyText} position={[0.00009, 0.00565, 0.00135]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.086' }} />
          </mesh>
          <mesh name="Key021" castShadow receiveShadow geometry={nodes.Key021.geometry} material={materials.Keycap} position={[0.17948, 0.0078, -0.02981]} userData={{ name: 'Key.021' }}>
            <mesh name="Text087" castShadow receiveShadow geometry={nodes.Text087.geometry} material={materials.KeyText} position={[0.00038, 0.00565, 0.00163]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.087' }} />
          </mesh>
          <mesh name="Key022" castShadow receiveShadow geometry={nodes.Key022.geometry} material={materials.Keycap} position={[0.13112, 0.0078, -0.02981]} userData={{ name: 'Key.022' }}>
            <mesh name="Text081" castShadow receiveShadow geometry={nodes.Text081.geometry} material={materials.KeyText} position={[-0.00019, 0.00565, 0.00181]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.081' }} />
          </mesh>
          <mesh name="Key023" castShadow receiveShadow geometry={nodes.Key023.geometry} material={materials.Keycap} position={[-0.18177, 0.0078, -0.03004]} userData={{ name: 'Key.023' }}>
            <mesh name="Text019" castShadow receiveShadow geometry={nodes.Text019.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.019' }} />
          </mesh>
          <mesh name="Key024" castShadow receiveShadow geometry={nodes.Key024.geometry} material={materials.Keycap} position={[-0.20601, 0.0078, -0.03004]} userData={{ name: 'Key.024' }}>
            <mesh name="Text018" castShadow receiveShadow geometry={nodes.Text018.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.018' }} />
          </mesh>
          <mesh name="Key029" castShadow receiveShadow geometry={nodes.Key029.geometry} material={materials.Keycap} position={[-0.23026, 0.0078, -0.03004]} userData={{ name: 'Key.029' }}>
            <mesh name="Text017" castShadow receiveShadow geometry={nodes.Text017.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.017' }} />
          </mesh>
          <mesh name="Key030" castShadow receiveShadow geometry={nodes.Key030.geometry} material={materials.Keycap} position={[-0.2545, 0.0078, -0.03004]} userData={{ name: 'Key.030' }}>
            <mesh name="Text016" castShadow receiveShadow geometry={nodes.Text016.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.016' }} />
          </mesh>
          <mesh name="Key031" castShadow receiveShadow geometry={nodes.Key031.geometry} material={materials.Keycap} position={[0.03643, 0.0078, -0.03004]} userData={{ name: 'Key.031' }}>
            <mesh name="Text028" castShadow receiveShadow geometry={nodes.Text028.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.028' }} />
          </mesh>
          <mesh name="Key032" castShadow receiveShadow geometry={nodes.Key032.geometry} material={materials.Keycap} position={[-0.15752, 0.0078, -0.03004]} userData={{ name: 'Key.032' }}>
            <mesh name="Text020" castShadow receiveShadow geometry={nodes.Text020.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.020' }} />
          </mesh>
          <mesh name="Key033" castShadow receiveShadow geometry={nodes.Key033.geometry} material={materials.Keycap} position={[-0.13328, 0.0078, -0.03004]} userData={{ name: 'Key.033' }}>
            <mesh name="Text021" castShadow receiveShadow geometry={nodes.Text021.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.021' }} />
          </mesh>
          <mesh name="Key034" castShadow receiveShadow geometry={nodes.Key034.geometry} material={materials.Keycap} position={[-0.10904, 0.0078, -0.03004]} userData={{ name: 'Key.034' }}>
            <mesh name="Text022" castShadow receiveShadow geometry={nodes.Text022.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.022' }} />
          </mesh>
          <mesh name="Key035" castShadow receiveShadow geometry={nodes.Key035.geometry} material={materials.Keycap} position={[-0.08479, 0.0078, -0.03004]} userData={{ name: 'Key.035' }}>
            <mesh name="Text023" castShadow receiveShadow geometry={nodes.Text023.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.023' }} />
          </mesh>
          <mesh name="Key036" castShadow receiveShadow geometry={nodes.Key036.geometry} material={materials.Keycap} position={[-0.06055, 0.0078, -0.03004]} userData={{ name: 'Key.036' }}>
            <mesh name="Text024" castShadow receiveShadow geometry={nodes.Text024.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.024' }} />
          </mesh>
          <mesh name="Key037" castShadow receiveShadow geometry={nodes.Key037.geometry} material={materials.Keycap} position={[-0.03631, 0.0078, -0.03004]} userData={{ name: 'Key.037' }}>
            <mesh name="Text025" castShadow receiveShadow geometry={nodes.Text025.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.025' }} />
          </mesh>
          <mesh name="Key038" castShadow receiveShadow geometry={nodes.Key038.geometry} material={materials.Keycap} position={[-0.01206, 0.0078, -0.03004]} userData={{ name: 'Key.038' }}>
            <mesh name="Text026" castShadow receiveShadow geometry={nodes.Text026.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.026' }} />
          </mesh>
          <mesh name="Key039" castShadow receiveShadow geometry={nodes.Key039.geometry} material={materials.Keycap} position={[0.01218, 0.0078, -0.03004]} userData={{ name: 'Key.039' }}>
            <mesh name="Text027" castShadow receiveShadow geometry={nodes.Text027.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.027' }} />
          </mesh>
          <mesh name="Key040" castShadow receiveShadow geometry={nodes.Key040.geometry} material={materials.Keycap} position={[0.05098, 0.0078, -0.00575]} userData={{ name: 'Key.040' }}>
            <mesh name="Text042" castShadow receiveShadow geometry={nodes.Text042.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.042' }} />
          </mesh>
          <mesh name="Key041" castShadow receiveShadow geometry={nodes.Key041.geometry} material={materials.Keycap} position={[-0.21536, 0.0078, -0.00575]} userData={{ name: 'Key.041' }}>
            <mesh name="Text031" castShadow receiveShadow geometry={nodes.Text031.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.031' }} />
          </mesh>
          <mesh name="Key042" castShadow receiveShadow geometry={nodes.Key042.geometry} material={materials.Keycap} position={[-0.19115, 0.0078, -0.00575]} userData={{ name: 'Key.042' }}>
            <mesh name="Text032" castShadow receiveShadow geometry={nodes.Text032.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.032' }} />
          </mesh>
          <mesh name="Key043" castShadow receiveShadow geometry={nodes.Key043.geometry} material={materials.Keycap} position={[-0.16694, 0.0078, -0.00575]} userData={{ name: 'Key.043' }}>
            <mesh name="Text033" castShadow receiveShadow geometry={nodes.Text033.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.033' }} />
          </mesh>
          <mesh name="Key044" castShadow receiveShadow geometry={nodes.Key044.geometry} material={materials.Keycap} position={[-0.14272, 0.0078, -0.00575]} userData={{ name: 'Key.044' }}>
            <mesh name="Text034" castShadow receiveShadow geometry={nodes.Text034.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.034' }} />
          </mesh>
          <mesh name="Key045" castShadow receiveShadow geometry={nodes.Key045.geometry} material={materials.Keycap} position={[-0.11851, 0.0078, -0.00575]} userData={{ name: 'Key.045' }}>
            <mesh name="Text035" castShadow receiveShadow geometry={nodes.Text035.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.035' }} />
          </mesh>
          <mesh name="Key046" castShadow receiveShadow geometry={nodes.Key046.geometry} material={materials.Keycap} position={[-0.0943, 0.0078, -0.00575]} userData={{ name: 'Key.046' }}>
            <mesh name="Text036" castShadow receiveShadow geometry={nodes.Text036.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.036' }} />
          </mesh>
          <mesh name="Key047" castShadow receiveShadow geometry={nodes.Key047.geometry} material={materials.Keycap} position={[-0.07008, 0.0078, -0.00575]} userData={{ name: 'Key.047' }}>
            <mesh name="Text037" castShadow receiveShadow geometry={nodes.Text037.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.037' }} />
          </mesh>
          <mesh name="Key048" castShadow receiveShadow geometry={nodes.Key048.geometry} material={materials.Keycap} position={[-0.04587, 0.0078, -0.00575]} userData={{ name: 'Key.048' }}>
            <mesh name="Text038" castShadow receiveShadow geometry={nodes.Text038.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.038' }} />
          </mesh>
          <mesh name="Key049" castShadow receiveShadow geometry={nodes.Key049.geometry} material={materials.Keycap} position={[-0.02166, 0.0078, -0.00575]} userData={{ name: 'Key.049' }}>
            <mesh name="Text039" castShadow receiveShadow geometry={nodes.Text039.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.039' }} />
          </mesh>
          <mesh name="Key050" castShadow receiveShadow geometry={nodes.Key050.geometry} material={materials.Keycap} position={[0.00256, 0.0078, -0.00575]} userData={{ name: 'Key.050' }}>
            <mesh name="Text040" castShadow receiveShadow geometry={nodes.Text040.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.040' }} />
          </mesh>
          <mesh name="Key051" castShadow receiveShadow geometry={nodes.Key051.geometry} material={materials.Keycap} position={[0.02677, 0.0078, -0.00575]} userData={{ name: 'Key.051' }}>
            <mesh name="Text041" castShadow receiveShadow geometry={nodes.Text041.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.041' }} />
          </mesh>
          <mesh name="Key052" castShadow receiveShadow geometry={nodes.Key052.geometry} material={materials.Keycap} position={[0.03995, 0.0078, 0.01854]} userData={{ name: 'Key.052' }}>
            <mesh name="Text056" castShadow receiveShadow geometry={nodes.Text056.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.056' }} />
          </mesh>
          <mesh name="Key053" castShadow receiveShadow geometry={nodes.Key053.geometry} material={materials.Keycap} position={[0.03093, 0.0078, 0.04283]} userData={{ name: 'Key.053' }}>
            <mesh name="Text069" castShadow receiveShadow geometry={nodes.Text069.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.069' }} />
          </mesh>
          <mesh name="Key054" castShadow receiveShadow geometry={nodes.Key054.geometry} material={materials.Keycap} position={[0.03831, 0.0078, 0.06711]} userData={{ name: 'Key.054' }}>
            <mesh name="Text084" castShadow receiveShadow geometry={nodes.Text084.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.084' }} />
          </mesh>
          <mesh name="Key055" castShadow receiveShadow geometry={nodes.Key055.geometry} material={materials.Keycap} position={[-0.19833, 0.0078, 0.06711]} userData={{ name: 'Key.055' }}>
            <mesh name="Text074" castShadow receiveShadow geometry={nodes.Text074.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.074' }} />
          </mesh>
          <mesh name="Key056" castShadow receiveShadow geometry={nodes.Key056.geometry} material={materials.Keycap} position={[-0.22246, 0.0078, 0.06711]} userData={{ name: 'Key.056' }}>
            <mesh name="Wizard002" castShadow receiveShadow geometry={nodes.Wizard002.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[Math.PI / 2, 0, 2.99465]} userData={{ name: 'Wizard.002' }} />
          </mesh>
          <mesh name="Key057" castShadow receiveShadow geometry={nodes.Key057.geometry} material={materials.Keycap} position={[-0.01026, 0.0078, 0.06711]} userData={{ name: 'Key.057' }}>
            <mesh name="Text082" castShadow receiveShadow geometry={nodes.Text082.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.082' }} />
          </mesh>
          <mesh name="Key058" castShadow receiveShadow geometry={nodes.Key058.geometry} material={materials.Keycap} position={[0.01403, 0.0078, 0.06711]} userData={{ name: 'Key.058' }}>
            <mesh name="Wizard001" castShadow receiveShadow geometry={nodes.Wizard001.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[Math.PI / 2, 0, 2.99465]} userData={{ name: 'Wizard.001' }} />
          </mesh>
          <mesh name="Key059" castShadow receiveShadow geometry={nodes.Key059.geometry} material={materials.Keycap} position={[-0.21129, 0.0078, 0.04283]} userData={{ name: 'Key.059' }}>
            <mesh name="Text059" castShadow receiveShadow geometry={nodes.Text059.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.059' }} />
          </mesh>
          <mesh name="Key060" castShadow receiveShadow geometry={nodes.Key060.geometry} material={materials.Keycap} position={[-0.18707, 0.0078, 0.04283]} userData={{ name: 'Key.060' }}>
            <mesh name="Text060" castShadow receiveShadow geometry={nodes.Text060.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.060' }} />
          </mesh>
          <mesh name="Key061" castShadow receiveShadow geometry={nodes.Key061.geometry} material={materials.Keycap} position={[-0.16285, 0.0078, 0.04283]} userData={{ name: 'Key.061' }}>
            <mesh name="Text061" castShadow receiveShadow geometry={nodes.Text061.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.061' }} />
          </mesh>
          <mesh name="Key062" castShadow receiveShadow geometry={nodes.Key062.geometry} material={materials.Keycap} position={[-0.13863, 0.0078, 0.04283]} userData={{ name: 'Key.062' }}>
            <mesh name="Text062" castShadow receiveShadow geometry={nodes.Text062.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.062' }} />
          </mesh>
          <mesh name="Key063" castShadow receiveShadow geometry={nodes.Key063.geometry} material={materials.Keycap} position={[-0.1144, 0.0078, 0.04283]} userData={{ name: 'Key.063' }}>
            <mesh name="Text063" castShadow receiveShadow geometry={nodes.Text063.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.063' }} />
          </mesh>
          <mesh name="Key064" castShadow receiveShadow geometry={nodes.Key064.geometry} material={materials.Keycap} position={[-0.09018, 0.0078, 0.04283]} userData={{ name: 'Key.064' }}>
            <mesh name="Text064" castShadow receiveShadow geometry={nodes.Text064.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.064' }} />
          </mesh>
          <mesh name="Key065" castShadow receiveShadow geometry={nodes.Key065.geometry} material={materials.Keycap} position={[-0.06596, 0.0078, 0.04283]} userData={{ name: 'Key.065' }}>
            <mesh name="Text065" castShadow receiveShadow geometry={nodes.Text065.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.065' }} />
          </mesh>
          <mesh name="Key066" castShadow receiveShadow geometry={nodes.Key066.geometry} material={materials.Keycap} position={[-0.04174, 0.0078, 0.04283]} userData={{ name: 'Key.066' }}>
            <mesh name="Text066" castShadow receiveShadow geometry={nodes.Text066.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.066' }} />
          </mesh>
          <mesh name="Key067" castShadow receiveShadow geometry={nodes.Key067.geometry} material={materials.Keycap} position={[-0.01751, 0.0078, 0.04283]} userData={{ name: 'Key.067' }}>
            <mesh name="Text067" castShadow receiveShadow geometry={nodes.Text067.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.067' }} />
          </mesh>
          <mesh name="Key068" castShadow receiveShadow geometry={nodes.Key068.geometry} material={materials.Keycap} position={[0.00671, 0.0078, 0.04283]} userData={{ name: 'Key.068' }}>
            <mesh name="Text068" castShadow receiveShadow geometry={nodes.Text068.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.068' }} />
          </mesh>
          <mesh name="Key069" castShadow receiveShadow geometry={nodes.Key069.geometry} material={materials.Keycap} position={[-0.22622, 0.0078, 0.01854]} userData={{ name: 'Key.069' }}>
            <mesh name="Text045" castShadow receiveShadow geometry={nodes.Text045.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.045' }} />
          </mesh>
          <mesh name="Key070" castShadow receiveShadow geometry={nodes.Key070.geometry} material={materials.Keycap} position={[-0.20203, 0.0078, 0.01854]} userData={{ name: 'Key.070' }}>
            <mesh name="Text046" castShadow receiveShadow geometry={nodes.Text046.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.046' }} />
          </mesh>
          <mesh name="Key071" castShadow receiveShadow geometry={nodes.Key071.geometry} material={materials.Keycap} position={[-0.17783, 0.0078, 0.01854]} userData={{ name: 'Key.071' }}>
            <mesh name="Text047" castShadow receiveShadow geometry={nodes.Text047.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.047' }} />
          </mesh>
          <mesh name="Key072" castShadow receiveShadow geometry={nodes.Key072.geometry} material={materials.Keycap} position={[-0.15363, 0.0078, 0.01854]} userData={{ name: 'Key.072' }}>
            <mesh name="Text048" castShadow receiveShadow geometry={nodes.Text048.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.048' }} />
          </mesh>
          <mesh name="Key073" castShadow receiveShadow geometry={nodes.Key073.geometry} material={materials.Keycap} position={[-0.12943, 0.0078, 0.01854]} userData={{ name: 'Key.073' }}>
            <mesh name="Text049" castShadow receiveShadow geometry={nodes.Text049.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.049' }} />
          </mesh>
          <mesh name="Key074" castShadow receiveShadow geometry={nodes.Key074.geometry} material={materials.Keycap} position={[-0.10523, 0.0078, 0.01854]} userData={{ name: 'Key.074' }}>
            <mesh name="Text050" castShadow receiveShadow geometry={nodes.Text050.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.050' }} />
          </mesh>
          <mesh name="Key075" castShadow receiveShadow geometry={nodes.Key075.geometry} material={materials.Keycap} position={[-0.08104, 0.0078, 0.01854]} userData={{ name: 'Key.075' }}>
            <mesh name="Text051" castShadow receiveShadow geometry={nodes.Text051.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.051' }} />
          </mesh>
          <mesh name="Key076" castShadow receiveShadow geometry={nodes.Key076.geometry} material={materials.Keycap} position={[-0.05684, 0.0078, 0.01854]} userData={{ name: 'Key.076' }}>
            <mesh name="Text052" castShadow receiveShadow geometry={nodes.Text052.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.052' }} />
          </mesh>
          <mesh name="Key077" castShadow receiveShadow geometry={nodes.Key077.geometry} material={materials.Keycap} position={[-0.03264, 0.0078, 0.01854]} userData={{ name: 'Key.077' }}>
            <mesh name="Text053" castShadow receiveShadow geometry={nodes.Text053.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.053' }} />
          </mesh>
          <mesh name="Key078" castShadow receiveShadow geometry={nodes.Key078.geometry} material={materials.Keycap} position={[-0.00844, 0.0078, 0.01854]} userData={{ name: 'Key.078' }}>
            <mesh name="Text054" castShadow receiveShadow geometry={nodes.Text054.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.054' }} />
          </mesh>
          <mesh name="Key079" castShadow receiveShadow geometry={nodes.Key079.geometry} material={materials.Keycap} position={[0.01576, 0.0078, 0.01854]} userData={{ name: 'Key.079' }}>
            <mesh name="Text055" castShadow receiveShadow geometry={nodes.Text055.geometry} material={materials.KeyText} position={[0, 0.00516, 0.002]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.055' }} />
          </mesh>
          <mesh name="Key080" castShadow receiveShadow geometry={nodes.Key080.geometry} material={materials.Keycap} position={[0.298, 0.00774, -0.0299]} userData={{ name: 'Key.080' }}>
            <mesh name="Text105" castShadow receiveShadow geometry={nodes.Text105.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.105' }} />
          </mesh>
          <mesh name="Key081" castShadow receiveShadow geometry={nodes.Key081.geometry} material={materials.Keycap} position={[0.24948, 0.00774, -0.0299]} userData={{ name: 'Key.081' }}>
            <mesh name="Text089" castShadow receiveShadow geometry={nodes.Text089.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.089' }} />
          </mesh>
          <mesh name="Key082" castShadow receiveShadow geometry={nodes.Key082.geometry} material={materials.Keycap} position={[0.24948, 0.00774, 0.04268]} userData={{ name: 'Key.082' }}>
            <mesh name="Text098" castShadow receiveShadow geometry={nodes.Text098.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.098' }} />
          </mesh>
          <mesh name="Key083" castShadow receiveShadow geometry={nodes.Key083.geometry} material={materials.Keycap} position={[0.24948, 0.00774, 0.01849]} userData={{ name: 'Key.083' }}>
            <mesh name="Text095" castShadow receiveShadow geometry={nodes.Text095.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.095' }} />
          </mesh>
          <mesh name="Key084" castShadow receiveShadow geometry={nodes.Key084.geometry} material={materials.Keycap} position={[0.24948, 0.00774, -0.00571]} userData={{ name: 'Key.084' }}>
            <mesh name="Text092" castShadow receiveShadow geometry={nodes.Text092.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.092' }} />
          </mesh>
          <mesh name="Key085" castShadow receiveShadow geometry={nodes.Key085.geometry} material={materials.Keycap} position={[0.27374, 0.00774, -0.00571]} userData={{ name: 'Key.085' }}>
            <mesh name="Text093" castShadow receiveShadow geometry={nodes.Text093.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.093' }} />
          </mesh>
          <mesh name="Key086" castShadow receiveShadow geometry={nodes.Key086.geometry} material={materials.Keycap} position={[0.27374, 0.00774, 0.01849]} userData={{ name: 'Key.086' }}>
            <mesh name="Text096" castShadow receiveShadow geometry={nodes.Text096.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.096' }} />
          </mesh>
          <mesh name="Key087" castShadow receiveShadow geometry={nodes.Key087.geometry} material={materials.Keycap} position={[0.27374, 0.00774, 0.04268]} userData={{ name: 'Key.087' }}>
            <mesh name="Text099" castShadow receiveShadow geometry={nodes.Text099.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.099' }} />
          </mesh>
          <mesh name="Key088" castShadow receiveShadow geometry={nodes.Key088.geometry} material={materials.Keycap} position={[0.27374, 0.00774, 0.06688]} userData={{ name: 'Key.088' }}>
            <mesh name="Text102" castShadow receiveShadow geometry={nodes.Text102.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.102' }} />
          </mesh>
          <mesh name="Key089" castShadow receiveShadow geometry={nodes.Key089.geometry} material={materials.Keycap} position={[0.27374, 0.00774, -0.0299]} userData={{ name: 'Key.089' }}>
            <mesh name="Text090" castShadow receiveShadow geometry={nodes.Text090.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.090' }} />
          </mesh>
          <mesh name="Key090" castShadow receiveShadow geometry={nodes.Key090.geometry} material={materials.Keycap} position={[0.22523, 0.00774, -0.00571]} userData={{ name: 'Key.090' }}>
            <mesh name="Text091" castShadow receiveShadow geometry={nodes.Text091.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.091' }} />
          </mesh>
          <mesh name="Key091" castShadow receiveShadow geometry={nodes.Key091.geometry} material={materials.Keycap} position={[0.22523, 0.00774, 0.01849]} userData={{ name: 'Key.091' }}>
            <mesh name="Text094" castShadow receiveShadow geometry={nodes.Text094.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.094' }} />
          </mesh>
          <mesh name="Key092" castShadow receiveShadow geometry={nodes.Key092.geometry} material={materials.Keycap} position={[0.22523, 0.00774, 0.04268]} userData={{ name: 'Key.092' }}>
            <mesh name="Text097" castShadow receiveShadow geometry={nodes.Text097.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.097' }} />
          </mesh>
          <mesh name="Key093" castShadow receiveShadow geometry={nodes.Key093.geometry} material={materials.Keycap} position={[0.22523, 0.00774, -0.0299]} userData={{ name: 'Key.093' }}>
            <mesh name="Text088" castShadow receiveShadow geometry={nodes.Text088.geometry} material={materials.KeyText} position={[0, 0.00516, 0.00045]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.088' }} />
          </mesh>
          <mesh name="Keys001" castShadow receiveShadow geometry={nodes.Keys001.geometry} material={materials.Keycap} position={[0.07088, 0.00796, 0.06709]} userData={{ name: 'Keys.001' }}>
            <mesh name="Text085" castShadow receiveShadow geometry={nodes.Text085.geometry} material={materials.KeyText} position={[0, 0.005, 0.00046]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.085' }} />
          </mesh>
          <mesh name="Keys002" castShadow receiveShadow geometry={nodes.Keys002.geometry} material={materials.Keycap} position={[-0.2451, 0.00802, 0.04282]} userData={{ name: 'Keys.002' }}>
            <mesh name="Text058" castShadow receiveShadow geometry={nodes.Text058.geometry} material={materials.KeyText} position={[0.00008, 0.005, 0.00046]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.058' }} />
          </mesh>
          <mesh name="Keys003" castShadow receiveShadow geometry={nodes.Keys003.geometry} material={materials.Keycap} position={[0.06718, 0.00797, 0.04284]} userData={{ name: 'Keys.003' }}>
            <mesh name="Text070" castShadow receiveShadow geometry={nodes.Text070.geometry} material={materials.KeyText} position={[-0.00001, 0.00499, 0.00046]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.070' }} />
          </mesh>
          <mesh name="Keys004" castShadow receiveShadow geometry={nodes.Keys004.geometry} material={materials.Keycap} position={[-0.25052, 0.00802, 0.06716]} userData={{ name: 'Keys.004' }}>
            <mesh name="Text072" castShadow receiveShadow geometry={nodes.Text072.geometry} material={materials.KeyText} position={[0.00006, 0.005, 0.00046]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.072' }} />
          </mesh>
          <mesh name="Keys005" castShadow receiveShadow geometry={nodes.Keys005.geometry} material={materials.Keycap} position={[-0.25248, 0.00802, 0.01848]} userData={{ name: 'Keys.005' }}>
            <mesh name="Text044" castShadow receiveShadow geometry={nodes.Text044.geometry} material={materials.KeyText} position={[0.00005, 0.005, 0.00046]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.044' }} />
          </mesh>
          <mesh name="Keys006" castShadow receiveShadow geometry={nodes.Keys006.geometry} material={materials.Keycap} position={[-0.24703, 0.00802, -0.00577]} userData={{ name: 'Keys.006' }}>
            <mesh name="Text030" castShadow receiveShadow geometry={nodes.Text030.geometry} material={materials.KeyText} position={[0.00008, 0.005, 0.00046]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.030' }} />
          </mesh>
          <mesh name="Keys007" castShadow receiveShadow geometry={nodes.Keys007.geometry} material={materials.Keycap} position={[0.06993, 0.00802, -0.03004]} userData={{ name: 'Keys.007' }}>
            <mesh name="Text029" castShadow receiveShadow geometry={nodes.Text029.geometry} material={materials.KeyText} position={[0.00008, 0.005, 0.00046]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.029' }} />
          </mesh>
          <mesh name="Keys008" castShadow receiveShadow geometry={nodes.Keys008.geometry} material={materials.Keycap} position={[0.23737, 0.00796, 0.06689]} userData={{ name: 'Keys.008' }}>
            <mesh name="Text100" castShadow receiveShadow geometry={nodes.Text100.geometry} material={materials.KeyText} position={[0, 0.005, 0.00046]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.100' }} />
          </mesh>
          <mesh name="Keys009" castShadow receiveShadow geometry={nodes.Keys009.geometry} material={materials.Keycap} position={[0.29803, 0.00802, 0.0544]} userData={{ name: 'Keys.009' }}>
            <mesh name="Text103" castShadow receiveShadow geometry={nodes.Text103.geometry} material={materials.KeyText} position={[0, 0.00493, 0.00091]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.103' }} />
          </mesh>
          <mesh name="Keys010" castShadow receiveShadow geometry={nodes.Keys010.geometry} material={materials.Keycap} position={[0.29803, 0.00802, 0.00603]} userData={{ name: 'Keys.010' }}>
            <mesh name="Text104" castShadow receiveShadow geometry={nodes.Text104.geometry} material={materials.KeyText} position={[0, 0.00493, 0.00091]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.104' }} />
          </mesh>
          <mesh name="Keys011" castShadow receiveShadow geometry={nodes.Keys011.geometry} material={materials.Keycap} position={[0.07473, 0.00803, 0.00814]} userData={{ name: 'Keys.011' }}>
            <mesh name="Text057" castShadow receiveShadow geometry={nodes.Text057.geometry} material={materials.KeyText} position={[-0.00362, 0.00453, 0.01083]} rotation={[0.11912, 0, 0]} scale={0.00785} userData={{ name: 'Text.057' }} />
          </mesh>
          <mesh name="Keys012" castShadow receiveShadow geometry={nodes.Keys012.geometry} material={materials.Keycap} position={[-0.10434, 0.00817, 0.06711]} userData={{ name: 'Keys.012' }}>
            <mesh name="Plane" castShadow receiveShadow geometry={nodes.Plane.geometry} material={materials.KeyText} position={[-0.00177, 0.00495, 0.00083]} userData={{ name: 'Plane' }} />
          </mesh>
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/home/models/Keyboard.glb')
